security:
  basic:
    enabled: false

management:
  security:
    enabled: false

# if your laptop is so f... slow just set this value
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000